name = "KalmanFilterTools"
uuid = "ec016732-9331-11e9-305f-d53cb440b85a"
authors = ["Michel Juillard <michel.juillard@mjui.fr>"]
version = "0.1.5"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.6"
